/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lookhub;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vip
 */
public class MessageKey extends javax.swing.JFrame {

    /**
     * Creates new form MessageKey
     */
    ImageIcon iconimg = new ImageIcon("src\\lookhub\\Images\\success.png");
    public MessageKey() {
        initComponents();
        this.setTitle("Look Hub - Message Key");
        java.awt.Image icon = Toolkit.getDefaultToolkit().getImage("src\\lookhub\\Images\\Unisex.png");  
        this.setIconImage(icon);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension size = tk.getScreenSize();
        this.setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        showkey();
    }
    public void showkey(){
        try {
            Connection con=DbUtil.loadDriver();
            ResultSet rs = DbUtil.getResultSet("SELECT * FROM `messagekey`");
            if (rs.next()) {
                CurrentKey.setText(rs.getString(2));
            }else{
                CurrentKey.setText("No Key Found");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgpane = new javax.swing.JPanel();
        msgpanel = new javax.swing.JPanel();
        msgkey = new javax.swing.JLabel();
        crntkey = new javax.swing.JLabel();
        nwkey = new javax.swing.JLabel();
        NewKey = new javax.swing.JTextField();
        CurrentKey = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        msgpane.setBackground(new java.awt.Color(38, 3, 3));

        msgpanel.setBackground(new java.awt.Color(204, 204, 204));

        msgkey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgkey.setText("Message Key");

        crntkey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crntkey.setText("Current Key");

        nwkey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nwkey.setText("New Key");

        NewKey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CurrentKey.setEditable(false);
        CurrentKey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Save.setText("Save Key");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout msgpanelLayout = new javax.swing.GroupLayout(msgpanel);
        msgpanel.setLayout(msgpanelLayout);
        msgpanelLayout.setHorizontalGroup(
            msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(msgpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(msgpanelLayout.createSequentialGroup()
                        .addComponent(nwkey, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewKey))
                    .addGroup(msgpanelLayout.createSequentialGroup()
                        .addComponent(crntkey, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentKey, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msgkey, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        msgpanelLayout.setVerticalGroup(
            msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(msgkey)
                .addGap(22, 22, 22)
                .addGroup(msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crntkey)
                    .addComponent(CurrentKey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewKey, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nwkey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(msgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout msgpaneLayout = new javax.swing.GroupLayout(msgpane);
        msgpane.setLayout(msgpaneLayout);
        msgpaneLayout.setHorizontalGroup(
            msgpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgpaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(msgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        msgpaneLayout.setVerticalGroup(
            msgpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgpaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(msgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int exitopt = JOptionPane.showConfirmDialog(this, "Do you really want to exit ?","EXIT",JOptionPane.YES_NO_OPTION);
        
        if(exitopt==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        if (NewKey.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter New Key ","KEY",JOptionPane.OK_OPTION);
        }else{
            int opt = JOptionPane.showConfirmDialog(this, "Do you really want to Save Changes ?","SAVE",JOptionPane.YES_NO_OPTION);
            if(opt==JOptionPane.YES_OPTION){
                try {
                    Connection con=DbUtil.loadDriver();
                    DbUtil.runQuery("DELETE FROM `messagekey` WHERE `Sr No` = 1");
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `messagekey`(`Sr No`, `msgkey`) VALUES (?,?)");
                    ps.setInt(1, 1);
                    ps.setString(2, NewKey.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Details Save SuccessFully","SAVED",JOptionPane.INFORMATION_MESSAGE,iconimg);
                    showkey();
                    con.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentKey;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField NewKey;
    private javax.swing.JButton Save;
    private javax.swing.JLabel crntkey;
    private javax.swing.JLabel msgkey;
    private javax.swing.JPanel msgpane;
    private javax.swing.JPanel msgpanel;
    private javax.swing.JLabel nwkey;
    // End of variables declaration//GEN-END:variables
}
