/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lookhub;

import java.awt.Toolkit;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author vip
 */
public class Pdfviewer extends javax.swing.JFrame {

    /**
     * Creates new form Pdfviewer
     */
    public Pdfviewer(String name,String billnos) {
        initComponents();
        this.setTitle("Look Hub - Pdf Viewer");
        java.awt.Image icon = Toolkit.getDefaultToolkit().getImage("src\\lookhub\\Images\\Unisex.png");  
        this.setIconImage(icon);
        
        try {
        String file = "C:\\pdfcreator\\"+name+billnos+".pdf";
           SwingController control=new SwingController();
            SwingViewBuilder factry=new SwingViewBuilder(control);
            billsheet=factry.buildViewerPanel();
            ComponentKeyBinding.install(control, billsheet);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                    control.getDocumentViewController()));
                   control.openDocument(file);
        bscroll.setViewportView(billsheet);  
        } catch (Exception ex) {
        }
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bscroll = new javax.swing.JScrollPane();
        billsheet = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout billsheetLayout = new javax.swing.GroupLayout(billsheet);
        billsheet.setLayout(billsheetLayout);
        billsheetLayout.setHorizontalGroup(
            billsheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        billsheetLayout.setVerticalGroup(
            billsheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        bscroll.setViewportView(billsheet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bscroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bscroll)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billsheet;
    private javax.swing.JScrollPane bscroll;
    // End of variables declaration//GEN-END:variables
}
